# Generated by Django 3.2.1 on 2021-05-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='num_of_lectures',
            field=models.PositiveIntegerField(default=1, verbose_name='Number of lectures'),
        ),
    ]
