# Generated by Django 3.2.1 on 2021-05-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_num_of_lectures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='num_of_lectures',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Number of lectures'),
        ),
    ]
