# Generated by Django 3.2.1 on 2021-05-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_num_of_lectures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='num_of_lectures',
            field=models.PositiveSmallIntegerField(default=1, error_messages={'CHECK constraint failed': 'Number is negative, enter positive one'}, help_text='Enter positive number, because negative call error', verbose_name='Number of lectures'),
        ),
    ]
